project:
  type: website

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

website:
  page-navigation: true
  twitter-card: true
  open-graph: true
  repo-actions: [issue]
  navbar:
    background: primary
    search: true
    right: 
      - icon: github
        href: "https://github.com/fligt/maxrf4u"
  sidebar:
    style: floating
  page-footer: "2024 Rijkserfgoedlaboratorium Amsterdam | Made with nbdev"

metadata-files: [nbdev.yml, sidebar.yml]
