# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/maxrf4u',
                'doc_host': 'https://fligt.github.io',
                'git_url': 'https://github.com/fligt/maxrf4u',
                'lib_path': 'maxrf4u'},
  'syms': { 'maxrf4u.absorption': {},
            'maxrf4u.fingerprints': {},
            'maxrf4u.iplotting': {},
            'maxrf4u.peak_pattern_puzzle_solver': {},
            'maxrf4u.speckles': {}}}
