# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Layers": "10_storage.ipynb",
         "raw_to_datastack": "10_storage.ipynb",
         "tree": "10_storage.ipynb",
         "underscorify": "10_storage.ipynb",
         "append": "10_storage.ipynb",
         "repack": "10_storage.ipynb",
         "max_and_sum_spectra": "10_storage.ipynb",
         "DataStack": "10_storage.ipynb",
         "DATASTACK_EXT": "10_storage.ipynb",
         "L": "10_storage.ipynb",
         "calibrate": "20_calibration.ipynb",
         "detector_angle": "20_calibration.ipynb",
         "RHODIUM_Ka": "20_calibration.ipynb",
         "IRON_Ka": "20_calibration.ipynb",
         "HotmaxAtlas": "30_hotmax.ipynb",
         "compute_hotmax_spectra": "30_hotmax.ipynb",
         "compute_hotmax_noise": "30_hotmax.ipynb",
         "get_patterns": "40_peak-pattern-puzzle.ipynb",
         "colorize": "40_peak-pattern-puzzle.ipynb",
         "plot_ptrn": "40_peak-pattern-puzzle.ipynb",
         "plot_patterns": "40_peak-pattern-puzzle.ipynb",
         "plot_puzzle": "40_peak-pattern-puzzle.ipynb",
         "all_elements": "40_peak-pattern-puzzle.ipynb",
         "eoi": "40_peak-pattern-puzzle.ipynb"}

modules = ["storage.py",
           "calibration.py",
           "hotmax.py",
           "peakpuzzle.py"]

doc_url = "https://fligt.github.io/maxrf4u/"

git_url = "https://github.com/fligt/maxrf4u/tree/main/"

def custom_doc_links(name): return None
